AY2122S2-CS2103T-T17-4/tp

docs/_config.yml, docs/_sass/minima/_base.scss
Fixes #15
Before: The site-wide settings is configured for Ab3.
After: Update site-wide settings to Abπ.
Proposed commit message:
Update site-wide settings
=> [#15] Update site-wide settings

docs/DeveloperGuide.md
Fixes #18 
Update DeveloperGuide. 
Update the target user profile and value proposition to match the project direction. 
Give use cases for a few representative user stories that need multiple steps to complete. 
Update Glossary and Non-Function requirements.
Before:
DeveloperGuide cannot fully cover ABπ v1.1.
After:
DeveloperGuide covers ABπ v1.1.
=> [#18]  Update DeveloperGuide.md

docs/DeveloperGuide.md
Reverts AY2122S2-CS2103T-T17-4/tp#17
PR does not follow the required project management workflow.
=> Revert "[#18]  Update DeveloperGuide.md"

docs/UserGuide.md
Fixes #20.
Previous UserGuide contains outdated information for the ``find`` command.
Updated UserGuide will more accurately reflect the ``find`` command.
=> [#20] Update UserGuide to contain information on new find command

docs/UserGuide.md
Fixes #24
Previous UserGuide contains does not contain information for memo command and no duplicate feature
Update UserGuide to include memo command and no duplicate feature.
=> [#24] Update UserGuide about memo command and no duplicate feature

docs/team/atmh.md
Fixes #29
Previous atmh.md does not contain information related to Abπ.
Update atmh.md to include an overview of Abπ and the headings of sections.
=> Update project portfolio page atmh.md

docs/team/tandeshao.md
Fixes #31
Previous `tandeshao.md` contained template information and does not accurately describe the work done for Abπ.
Update `tandeshao.md` to include a more accurate project description of Abπ and added headings for the various sections.
=> [#31] Update Project Portfolio Page tandeshao.md

docs/UserGuide.md
=> [#39] Update UserGuide.md with copyemails

docs/team/lovemathboy.md
=> [#38] Update Project Portfolio Page for lovemathboy.md

docs/UserGuide.md
Fixes #21 
Previous UserGuide does not contain invoke feature.
Update UserGuide to include invoke command.
=> [#21] Update UserGuide.md with invoke feature

docs/DeveloperGuide.md
Fixes #26 
Previous DeveloperGuide include outdated information, which is for ab3 rather than abπ.
Update DeveloperGuide to include correct information about abπ.
=> [#26] Update DeveloperGuide.md

docs/UserGuide.md
Fixes #44
Previous UserGuide.md contain release URL of Ab3.
Update UserGuide.md to include release URL of Abπ.
=> [#44] Update UserGuide.md to remove all traces of Ab3

docs/UserGuide.md
Fixes #46 
Previous UserGuide.md contains `addressbook.jar`
Updated UserGuide.md to contain `abpie.jar`
=> Update addressbook.jar to abpie.jar

docs/index.md
Fixes #48 
Previous UserGuide.md contain information about Ab3.
Update UserGuide.md to include information about Abπ.
=> [#48] Update index.md to remove all traces of Ab3 

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/MemoCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Memo.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
Fixes #57
Previous Memo, Find, Add, Edit command was missing some Javadoc. JUnit tests did not cover some scenarios.
Update the Javadoc of Memo, Find, Add and Edit command. Added more JUnit tests to increase coverage.
=> [#57] Update Javadoc and JUnit for Memo, Find, Add and Edit command

src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/CopyEmailsCommandTest.java
Fixes #9 
Add copyemails command.
=> [#9] Add copyemails command.

src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml
Fixes #71.
Change JavaFX version so that the team can load the FXML files.
=> [#71] Change JavaFX version in the FXML files. 

src/main/java/seedu/address/logic/parser/ArgumentMultimap.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java
Fixes #75.
Add unit tests for ``ArgumentMultiMap`` class to ensure that the class is free of bugs.
=> [#75] Add tests for ArgumentMultiMap class

src/main/java/seedu/address/logic/parser/AddressBookParser.java
Fixes #87
Add logger to `AddressBookParser.java` to keep track of logs.
=> [#87] Add logging to AddressBookParser.java

src/main/java/seedu/address/model/util/SampleDataUtil.java
Fixes #95
Previous `SampleDataUtil.java` memos were empty.
Update the memos to contain miscellaneous data about the contact.
=> [#95] Update memo of SampleDataUtil.java

src/main/java/seedu/address/MainApp.java
Fixes #99
Previous version number in `MainApp.java` was v0.2.0.
Update version number to v1.3.0.
=> [#99] Update version number in MainApp.java to v1.3.0

docs/DeveloperGuide.md, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/PersonAttribute.java
Fixes #106.
Updates the design considerations in DeveloperGuide to contain more elaboration about the implementation of the find feature.
=> [#106]Update Design Considerations in DeveloperGuide

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/StateAddressBook.java, src/main/java/seedu/address/model/person/Memo.java
Fixes #113
Add logging to `UndoCommand`, `RedoCommand`, `AddCommandParser`, `EditCommandParser`, `AddressBookParser`. Add assertion to `StateAddressBook`.
=> [#113] Add logging and assertion to several classes

src/main/java/seedu/address/logic/commands/CopyEmailsCommand.java
Enable logging for CopyEmailsCommand
=> Enable logging for CopyEmailsCommand

docs/UserGuide.md, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Fixes #134.
Add unit testng for `ModelManager#deleteAllPerson(ObservableList<Person>)`.
=> [#134] Add test for ModelManager#deleteAllPerson(ObservableList<Person>)

docs/UserGuide.md
Fixes #156
Improve UserGuide.md formatting, such as ordering of command summary and page breaks.
=> [#156] Improve UserGuide.md formatting 

docs/DeveloperGuide.md, docs/UserGuide.md
Fixes #164 
Add Table of Contents and update glossary of `DeveloperGuide.md`
=> [#164] Improve DeveloperGuide.md Formatting

src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Phone.java, src/test/java/seedu/address/model/person/AddressTest.java
=> [#117] Limit number of characters for Name, Address, Email and Phone 

docs/UserGuide.md
Fixes #167 
Refine `UserGuide.md` content based on our CS2101 TA's comments.
=> [#167] Refine UserGuide.md content

src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/parser/AddTagCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/ui/PersonListPanel.java
Fixes #170.
Add AddTagCommand such that new tags can be appended to the back of the existing person tag set.
=> [#170] Add AddTagCommand

docs/UserGuide.md, src/main/java/seedu/address/model/person/predicate/DomainMatchPredicate.java
Fixes #181.
Update UserGuide with relevant information for AddTagCommand and ScrubCommand.
=> [#181]Update UserGuide with AddTagCommand and ScrubCommand

docs/UserGuide.md
=> [#189] Update UG with view command

src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
This fixes Tag size issue that closes #174 ,
also fixes #176 which allows any characters to be in name.
=> [#174][#176] Limit tag size and Change name to allow all characters

src/main/java/seedu/address/MainApp.java
Fixes #193 
Update version to v1.3.1.
=> [193] Update version to v1.3.1

docs/UserGuide.md
Fixes #195.
Update documentation to reflect the current information of the scrub command feature.
=> [#195] Update documentation on ScrubCommand

src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> Update Tag to allow everything

src/test/java/seedu/address/logic/commands/RedoCommandTest.java, src/test/java/seedu/address/logic/commands/UndoCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/StateAddressBookTest.java, src/test/java/seedu/address/model/person/ContactedDateTest.java, src/test/java/seedu/address/model/person/MemoTest.java, src/test/java/seedu/address/testutil/MemoUtil.java
Fixes #241
Add EP comments for `MemoTest`, `ContactedDateTest`, `StateAddressBookTest` and `ParserUtilTest`.
=> [#241] EP comments for MemoTest, ContactedDateTest, StateAddressBookTest and ParserUtilTest

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
Fixes #224
Improve the messages with the word "(case-insensitive)" to the messages to be more explicit.
=> [#244] Improve AddTagCommand and DeleteTagCommand messages

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/AddTagCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Fixes #200.
Previous message for invalid index displays invalid command format.
Update the message to display an invalid index instead.
=> [#200] Error message for incorrect index given 

src/main/java/seedu/address/model/person/Email.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/predicate/PartialWordMatchPredicateTest.java
=> [#235] Fix email to have at least one period

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/ContactedDate.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Memo.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/ExactTagComparator.java, src/main/java/seedu/address/ui/DetailedPersonDisplay.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DetailedPersonDisplay.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/ResultDisplay.fxml, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/ContactedDateTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/MemoTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/PhoneTest.java
Fixes #199 
Fixes #204 
Fixes #210 
Fixes #212
=> [#199][#204][#210][#212] Fix bugs from PE-D

src/main/java/seedu/address/model/person/Phone.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
=> [#211]phone number to allow space and plus

src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/model/person/PhoneTest.java
=> [#261] Fix phone

src/main/java/seedu/address/MainApp.java
Fixes #272 
Update Abπ version to v1.4.ea for internal PE-D testing.
=> [#272] Update Abπ version to v1.4.ea 

docs/UserGuide.md
Fixes #274 
Update `UserGuide.md` Quick Start section and improve formatting.
=> [#274] Update UserGuide Quick Start section and improve formatting

docs/team/tandeshao.md
Fixes #271.
Previous PPP file(tandeshao.md) is outdated.
Update PPP file (tandeshao.md) with new and updated information.
=> [#271] Update PPP for tandeshao.md

docs/UserGuide.md
Fixes #282
Improve UG formatting, add details about max integer and chronological ordering of contacts.
=> [#282] Improve UG formatting, add details about max integer and chronological ordering of contacts

docs/UserGuide.md, docs/index.md
Fixes #286 
Update `index.md`.
=> [#286] Update `index.md`

docs/DeveloperGuide.md
Fixes #290 
Update non-functional requirement and glossary.
=> [#290] Update non-functional requirement and glossary 

docs/team/xpzmichael.md
=> [#289] Update xpzmichael.md

docs/DeveloperGuide.md
=> [#295] Update instruction for manual testing in DeveloperGuide

docs/DeveloperGuide.md, docs/UserGuide.md
Fixes #299.
Previous DG has no conventions.
Add conventions into DG.
=> [#299] Add conventions in DG

docs/DeveloperGuide.md
Fixes #301.
Previous conventions table in DG is in the wrong format.
Update conventions table to a proper format.
=> [#301] Fix conventions table

docs/team/tandeshao.md
Fixes #303.
Previous PPP contains outdated information for DG contributions.
Update PPP to contain updated information for DG contributions.
=> [#303] Update PPP for tandeshao.md (DG contributions)

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/commons/util/FileUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/person/UniquePersonList.java
Fixes #256.
Previous DG has no documentation on backup feature.
Update DG to contain documentation on backup feature.
=> [#256] Add backup documentation in DG

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/StateAddressBook.java
Fixes #320
Tidy up JavaDocs formatting.
=> [#320] Tidy up JavaDocs
