AY2122S2-CS2103T-T17-4/tp

README.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
Fixes #6 
Previous uniqueness check is based on exact same names, which does not make sense as people can have same names.
Update Abπ to check for uniqueness based on phone number and email.
=> [#6] Uniqueness check for phone number and email

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Fixes #52
Previous edit command did not support memo and did not ensure uniqueness of phone number and email.
Updated edit command to support memo and prevent duplicated phone number and email.
=> [#52] Enhance edit to support memo and ensure uniqueness of phone number / email

src/test/java/seedu/address/logic/commands/RedoCommandTest.java, src/test/java/seedu/address/model/StateAddressBookTest.java
Fixes #104
Previous helper method names in StateAddressBookTest and RedoCommandTest class were misleading.
Refactor the method names to better represent its functionality.
=> [#104] Refactor helper method names in StateAddressBookTest and RedoCommandTest class

src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/ArgumentMultimap.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Memo.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/ArgumentMultimapTest.java, src/test/java/seedu/address/model/person/MemoTest.java, src/test/java/seedu/address/testutil/MemoUtil.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #120
Previous implementation of empty `Memo` is that each `Person` will have their own `Memo` object that is an empty string. Furthermore, if `Memo` is empty, there would be an awkward blank row in the UI.
Update implementation such that all `Person` with empty memos will share the same `EMPTY_MEMO` object and update UI such that if `Memo` is empty, the blank row will not be shown.
=> [#120] Update empty memo logic and UI for memo

src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Fixes #135.
Improve on test cases for `ContactedDateMatchPredicate` and `FindCommandParser`
=> [#135] Improve on tests for ContactedDateMatchPredicate

docs/UserGuide.md
Fixes #158
Previous UserGuide.md tables were cut off when converted to pdf.
Improve the page breaks so that tables will not be cut off when converted to pdf.
=> [#158] Improve UserGuide.md page breaks when converted to pdf

docs/UserGuide.md
Fixes #160 
Previous `UserGuide.md` sections are getting cut off when converted to PDF
Refine the page breaks to ensure each section is displayed properly without getting cut off when converted to PDF.
=> [#160] Refine UserGuide.md page breaks when converted to PDF

src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Fixes #162 
Previous `AddressBookParserTest.java` did not include tests for `copyemails`, `previous` and `next`.
Add JUnit tests for the commands `copyemails`, `previous` and `next` in `AddressBookParserTest.java` .
=> [#162] Add JUnit tests for AddressBookParserTest.java

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/ContactedDate.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Fixes #172
Add `DeleteTagCommand` which allows users to delete one or more tags of a specified index in the address book.
=> [#172] Add DeleteTagCommand

docs/UserGuide.md
Fixes #179 
Reformat the features, command summary and FAQ section of `UserGuide.md` and update it with `DeleteTagCommand` details.
=> [#179] Reformat UserGuide.md and update with DeleteTagCommand details

src/main/java/seedu/address/model/person/Person.java
Fixes #183 
Previous `Person#toString()` appended tags not in sorted order and there was no separator. E.g., if a person has the tags "friends", "colleague", "owesMoney", `Person#toString()` may append the tags as "friendsowesMoneycolleague".
Update `Person#toString()` to append tags in sorted order with brackets as separators, i.e., using the above example, `Person#toString()` will append the tags as "[colleague][friends][owesMoney]".
=> [#183] Update Person#toString()

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/parser/ArgumentMultimap.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/ScrubCommandParser.java, src/main/java/seedu/address/model/person/predicate/FindPersonPredicate.java, src/main/java/seedu/address/model/person/predicate/ScrubPersonPredicate.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/model/person/predicate/FindPersonPredicateTest.java, src/test/java/seedu/address/model/person/predicate/ScrubPersonPredicateTest.java
Fixes #191.
Change conditions such that `find p/999 n/alex` is semantically the same as finding all contacts with phone number 999 AND with the name Alex.
=> [#191] Update Find Command to allow stricter search conditions

docs/UserGuide.md
Fixes #201, Fixes #213
- Fix incorrect syntax for example command (Missing space)
- Add a proper hyperlink to "here" in "1.1 Conventions"
=> [#201][#213] Fix minor UserGuide.md bugs

src/main/java/seedu/address/model/person/ContactedDate.java
Fixes #207
Improved the message constraint when a user enters a `ContactedDate` in the wrong format.
=> [#207] Improve error message for incorrect date

docs/UserGuide.md
Fixes #221
Add a note to the `Deleting tags of a person` section of `UserGuide.md` to indicate how to remove all tags via the `Editing a person` section.
=> [#221] Update UserGuide.md to indicate how to remove all tags

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Memo.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/MemoTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/PhoneTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/MemoUtil.java
Fixes #222, Fixes #224, Fixes #225
Previous `Person#equal()` is true if phone or email is the same. This means that all contacts in the address book have unique phone and unique email. This is decided to be too restrictive.
Update `Person#equal()` to be true only if name, phone, email are the same. This allows greater flexibility in the address book, i.e., contacts are only considered as duplicates if name, phone and email are identical.  The following changes are made:
1. Update `Person#equal()` to be true only if name, phone and email are identical.
2. Update `#equal()` of `Name`, `Email`, `Address`, `Memo`, `Tag` to ignore case difference.
3. Update `#hasCode()` of `Name`, `Email`, `Address`, `Memo`, `Tag` with `String#toLowerCase()`.
4. Update test cases for `Person`, `AddCommand`, …
=> [#222][#224][#225] Revamp equals for Person and person attributes

docs/UserGuide.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ScrubCommand.java, src/test/java/seedu/address/logic/commands/ScrubCommandTest.java
Fixes #208 , Fixes #215 , Fixes #218 , Fixes #223 , Fixes #229 , Fixes #230  and Fixes #231.
Previous version of the user guide does not provide accurate and detailed information for the `scrub` and `find` commands.
Also, some of the message output from the `find` and `scrub` commands was ambiguous.
Update the user guide to contain more useful and relevant information. 
Change output message for the `find` and `scrub` commands for a better user experience.
=> [#208][#215][#218][#223][#229][#230][#231] Fix issues from PE-D

src/test/java/seedu/address/logic/commands/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Fixes #253 .
Previously there was no unit testing done for both the `AddTagCommand` class and the `AddTagCommandParser` class.
Add new unit tests for both classes in `AddTagCommandTest` and `AddTagCommandParserTest`.
=> [#253] Add tests to AddTag command and AddTagCommandParser class

docs/UserGuide.md, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/ContactedDate.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Memo.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/model/person/PhoneTest.java
Fixes #263
Previous `Phone#equals(Object)` considered "+65 98765432" and "+6598765432" to be different.
Update `Phone#equals(Object)` to ignore white spaces, such that "+65 98765432" and "+6598765432" is considered equal. This is better reflect reality, in that phone numbers are identical even if one have white spaces between them.
=> [#263] Revamp equality for phone numbers 

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Phone.java
Fixes #269 
Previous `Phone#removeAllWhiteSpace(String)` removes all spaces, but a identical function was implemented in `StringUtil` as well.
Remove duplicated code `Phone#removeAllWhiteSpace(String)` and replace it with `StringUtil#removeSpaces(String)`.
=> [#269] Remove duplicated code Phone#removeAllWhiteSpace(String)

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/commands/ViewCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/AddTagCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Fixes #279
Improve invalid command message for `edit`, `addtag`, `deletetag`, `delete` and `view`.
=> [#279] Improve invalid command message
